In [2]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.2.1 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/51/27/bf9436dd0a4fc3130acec0828951c7ef96a0631969613a9a35744baf27f6/pandas-3.0.0-cp311-cp311-win_amd64.whl.metadata
  Downloading pandas-3.0.0-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Obtaining dependency information for tzdata from https://files.pythonhosted.org/packages/c7/b0/003792df09decd6849a5e39c28b513c06e84436a54440380862b5aeff25d/tzdata-2025.3-py2.py3-none-any.whl.metadata
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB 640.0 kB/s eta 0:00:16
   ---------------------------------------- 0.1/9.9 MB 919.0 kB/s eta 0:00:11
    --------------------------------------- 0.2/9.9 MB 1.7 MB/s eta 0:00:06
   - -------------------------------------- 0.4/9.9 MB 2.1 MB/s eta 0:00:05
   -- ------------------------------------- 0.6/9.9 MB 2.5 MB/s eta 0:00:04
   -- ------------------------------------- 0.7/9.9 MB 2.7 MB/s eta 0:00:04
   --- ------------------------------------ 0.9/9.9 MB 2.9 MB/s eta 0:00:04
   ---- ----------------------------------- 1.1/9.9 MB 3.1 MB/s eta 0:00:03
   ----- ---------------------------------- 1.3/9.9 MB 3.1 MB/s eta 0:00:03
   ----- ---------------------------------- 1.4/9.9 MB 3.2 MB/s eta 0:00:03
   ------ --------------------------------- 1.6/9.9 MB 3.3 MB/s eta 0:00:03
   ------- -------------------------------- 1.8/9.9 MB 3.3 MB/s eta 0:00:03
   -------- ------------------------------- 2.0/9.9 MB 3.4 MB/s eta 0:00:03
   -------- ------------------------------- 2.2/9.9 MB 3.4 MB/s eta 0:00:03
   --------- ------------------------------ 2.3/9.9 MB 3.5 MB/s eta 0:00:03
   ---------- ----------------------------- 2.5/9.9 MB 3.5 MB/s eta 0:00:03
   ---------- ----------------------------- 2.7/9.9 MB 3.5 MB/s eta 0:00:03
   ----------- ---------------------------- 2.9/9.9 MB 3.5 MB/s eta 0:00:02
   ------------ --------------------------- 3.1/9.9 MB 3.5 MB/s eta 0:00:02
   ------------- -------------------------- 3.2/9.9 MB 3.6 MB/s eta 0:00:02
   ------------- -------------------------- 3.4/9.9 MB 3.6 MB/s eta 0:00:02
   -------------- ------------------------- 3.6/9.9 MB 3.6 MB/s eta 0:00:02
   --------------- ------------------------ 3.8/9.9 MB 3.6 MB/s eta 0:00:02
   ---------------- ----------------------- 4.0/9.9 MB 3.6 MB/s eta 0:00:02
   ---------------- ----------------------- 4.1/9.9 MB 3.7 MB/s eta 0:00:02
   ----------------- ---------------------- 4.3/9.9 MB 3.7 MB/s eta 0:00:02
   ------------------ --------------------- 4.5/9.9 MB 3.7 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.9 MB 3.7 MB/s eta 0:00:02
   ------------------- -------------------- 4.9/9.9 MB 3.7 MB/s eta 0:00:02
   -------------------- ------------------- 5.0/9.9 MB 3.7 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.9 MB 3.7 MB/s eta 0:00:02
   --------------------- ------------------ 5.4/9.9 MB 3.7 MB/s eta 0:00:02
   ---------------------- ----------------- 5.6/9.9 MB 3.7 MB/s eta 0:00:02
   ----------------------- ---------------- 5.8/9.9 MB 3.7 MB/s eta 0:00:02
   ------------------------ --------------- 6.0/9.9 MB 3.7 MB/s eta 0:00:02
   ------------------------ --------------- 6.1/9.9 MB 3.7 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.9 MB 3.7 MB/s eta 0:00:01
   -------------------------- ------------- 6.5/9.9 MB 3.7 MB/s eta 0:00:01
   --------------------------- ------------ 6.7/9.9 MB 3.7 MB/s eta 0:00:01
   --------------------------- ------------ 6.9/9.9 MB 3.7 MB/s eta 0:00:01
   ---------------------------- ----------- 7.0/9.9 MB 3.7 MB/s eta 0:00:01
   ----------------------------- ---------- 7.2/9.9 MB 3.7 MB/s eta 0:00:01
   ----------------------------- ---------- 7.4/9.9 MB 3.7 MB/s eta 0:00:01
   ------------------------------ --------- 7.5/9.9 MB 3.8 MB/s eta 0:00:01
   ------------------------------- -------- 7.7/9.9 MB 3.8 MB/s eta 0:00:01
   ------------------------------- -------- 7.9/9.9 MB 3.8 MB/s eta 0:00:01
   -------------------------------- ------- 8.0/9.9 MB 3.7 MB/s eta 0:00:01
   --------------------------------- ------ 8.2/9.9 MB 3.8 MB/s eta 0:00:01
   --------------------------------- ------ 8.4/9.9 MB 3.7 MB/s eta 0:00:01
   ---------------------------------- ----- 8.6/9.9 MB 3.7 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.9 MB 3.8 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.9 MB 3.7 MB/s eta 0:00:01
   ------------------------------------ --- 9.1/9.9 MB 3.7 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 3.7 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 3.7 MB/s eta 0:00:01
   -------------------------------------- - 9.6/9.9 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  9.8/9.9 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 3.7 MB/s eta 0:00:00
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
   ---------------------------------------- 0.0/348.5 kB ? eta -:--:--
   --------------------- ------------------ 184.3/348.5 kB 3.7 MB/s eta 0:00:01
   ---------------------------------------  348.2/348.5 kB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 348.5/348.5 kB 3.6 MB/s eta 0:00:00
Installing collected packages: tzdata, pandas
Successfully installed pandas-3.0.0 tzdata-2025.3

[notice] A new release of pip is available: 23.2.1 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import numpy as np

In [5]:
s1=pd.Series([1,2,3,4],index=['ahmed','said','hussien','ali'])
s1

ahmed      1
said       2
hussien    3
ali        4
dtype: int64

In [6]:
s1=pd.Series([1,2,3,4],index=['ahmed','said','hussien','ali'])
s1['ali']

np.int64(4)

In [16]:
arr=np.array([1,2,3,4,5])
s1=pd.Series([1,2,3,4],index=['ahmed','said','hussien','ali'])
s1.iloc[1]
s2=pd.Series(arr,index=['a','s','h','v','x'])
s2

a    1
s    2
h    3
v    4
x    5
dtype: int64

In [17]:
arr=np.array([1,2,3,4,5])
s1=pd.Series([1,2,3,4],index=['ahmed','said','hussien','ali'])
s1.iloc[1]
s2=pd.Series(arr,index=['a','s','h','v','x'])
s2.values

array([1, 2, 3, 4, 5])

In [18]:
arr=np.array([1,2,3,4,5])
s1=pd.Series([1,2,3,4],index=['ahmed','said','hussien','ali'])
s1.iloc[1]
s2=pd.Series(arr,index=['a','s','h','v','x'])
s2.index

Index(['a', 's', 'h', 'v', 'x'], dtype='str')

In [20]:
arr=np.array([1,2,3,4,5])
s1=pd.Series([1,2,3,4],index=['ahmed','said','hussien','ali'])
s1.iloc[1]
s2=pd.Series(arr,index=['a','s','h','v','x'])
s2+10

a    11
s    12
h    13
v    14
x    15
dtype: int64

In [18]:
df1=pd.DataFrame({'name':['omar','ahmed','hosssam'],
                  'age':[10,20,30],
                  'job':['doctor','engineer','accountant']})
df1

      name  age         job
0     omar   10      doctor
1    ahmed   20    engineer
2  hosssam   30  accountant

In [19]:
df1=pd.DataFrame({'name':['omar','ahmed','hossam'],
'age':[10,20,30],
'job':['doctor','engineer','accountant']})
df1
records=[{'name':'omar','age':15,'job':'eng'},
         {'name':'said','age':50,'job':'doc'},
         {'name':'fawzy','age':40,'job':'lawyer'}]
df2=pd.DataFrame(records)
df2

    name  age     job
0   omar   15     eng
1   said   50     doc
2  fawzy   40  lawyer

In [20]:
records=[{'name':'omar','age':15,'job':'eng'},
         {'name':'said','age':50,'job':'doc'},
         {'name':'fawzy','age':40,'job':'lawyer'}]
df2=pd.DataFrame(records)
df2

    name  age     job
0   omar   15     eng
1   said   50     doc
2  fawzy   40  lawyer

# domain knowledge

In [13]:
import pandas as pd
import plotly.express as px

df=pd.read_csv('titanic.csv')
df['fam_size']=df['Parch']+df['SibSp']
df=df.drop(columns=['SibSp','Parch'])
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked,fam_size
0,892,0,3,"Kelly, Mr. James",male,34.5,330911,7.8292,NaN,Q,0
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,363272,7.0000,NaN,S,1
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,240276,9.6875,NaN,Q,0
3,895,0,3,"Wirz, Mr. Albert",male,27.0,315154,8.6625,NaN,S,0
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,3101298,12.2875,NaN,S,2

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [7]:
df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q

In [9]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [10]:
df.tail(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    str
 4   Sex          418 non-null    str
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    str
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     str
 11  Embarked     418 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 39.3 KB

In [12]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [35]:
df.describe(include='object')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_3648\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

                    Name   Sex    Ticket            Cabin Embarked
count                418   418       418               91      418
unique               418     2       363               76        3
top     Kelly, Mr. James  male  PC 17608  B57 B59 B63 B66        S
freq                   1   266         5                3      270

In [65]:
df_numeric=df.drop(columns=['Name','Sex','Ticket','Cabin','Embarked'])
df_numeric['realatives']=df_numeric['sibSp']+df_numeric['Parch']
df_numeric.head()
df_numeric[['realatives','SibSp']]

KeyError: 'sibSp'

In [50]:
df.loc[400]

PassengerId                       1292
Survived                             1
Pclass                               1
Name           Bonnell, Miss. Caroline
Sex                             female
Age                               30.0
SibSp                                0
Parch                                0
Ticket                           36928
Fare                          164.8667
Cabin                               C7
Embarked                             S
Name: 400, dtype: object

In [53]:
df.loc[[400,401,3,5,102]]['Survived'][400]

np.int64(1)

In [61]:
df_numeric>10

     PassengerId  Survived  Pclass    Age  SibSp  Parch   Fare
0           True     False   False   True  False  False  False
1           True     False   False   True  False  False  False
2           True     False   False   True  False  False  False
3           True     False   False   True  False  False  False
4           True     False   False   True  False  False   True
..           ...       ...     ...    ...    ...    ...    ...
413         True     False   False  False  False  False  False
414         True     False   False   True  False  False   True
415         True     False   False   True  False  False  False
416         True     False   False  False  False  False  False
417         True     False   False  False  False  False   True

[418 rows x 7 columns]

In [58]:
df_numeric[df_numeric>10]

     PassengerId  Survived  Pclass   Age  SibSp  Parch      Fare
0            892       NaN     NaN  34.5    NaN    NaN       NaN
1            893       NaN     NaN  47.0    NaN    NaN       NaN
2            894       NaN     NaN  62.0    NaN    NaN       NaN
3            895       NaN     NaN  27.0    NaN    NaN       NaN
4            896       NaN     NaN  22.0    NaN    NaN   12.2875
..           ...       ...     ...   ...    ...    ...       ...
413         1305       NaN     NaN   NaN    NaN    NaN       NaN
414         1306       NaN     NaN  39.0    NaN    NaN  108.9000
415         1307       NaN     NaN  38.5    NaN    NaN       NaN
416         1308       NaN     NaN   NaN    NaN    NaN       NaN
417         1309       NaN     NaN   NaN    NaN    NaN   22.3583

[418 rows x 7 columns]

In [60]:
df_numeric[df_numeric>10].head()

   PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0          892       NaN     NaN  34.5    NaN    NaN      NaN
1          893       NaN     NaN  47.0    NaN    NaN      NaN
2          894       NaN     NaN  62.0    NaN    NaN      NaN
3          895       NaN     NaN  27.0    NaN    NaN      NaN
4          896       NaN     NaN  22.0    NaN    NaN  12.2875

In [ ]:
df_numeric

In [5]:

df9=pd.read_csv('fifa_eda.csv')
df9

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [6]:
x=df9.head()
print(x)

       ID               Name  Age Nationality  Overall  Potential  \
0  158023           L. Messi   31   Argentina       94         94
1   20801  Cristiano Ronaldo   33    Portugal       94         94
2  190871          Neymar Jr   26      Brazil       92         93
3  193080             De Gea   27       Spain       91         93
4  192985       K. De Bruyne   27     Belgium       91         92

                  Club     Value   Wage Preferred Foot  \
0         FC Barcelona  110500.0  565.0           Left
1             Juventus   77000.0  405.0          Right
2  Paris Saint-Germain  118500.0  290.0          Right
3    Manchester United   72000.0  260.0          Right
4      Manchester City  102000.0  355.0          Right

   International Reputation  Skill Moves Position  Joined  \
0                       5.0          4.0       RF    2004
1                       5.0          5.0       ST    2018
2                       5.0          5.0       LW    2017
3                       4.0          1.0       GK    2011
4                       4.0          4.0      RCM    2015

  Contract Valid Until    Height  Weight  Release Clause
0           2021-01-01  5.583333   159.0        226500.0
1           2022-01-01  6.166667   183.0        127100.0
2           2022-01-01  5.750000   150.0        228100.0
3           2020-01-01  6.333333   168.0        138600.0
4           2023-01-01  5.916667   154.0        196400.0

In [86]:
df9.info

<bound method DataFrame.info of            ID                Name  Age Nationality  Overall  Potential  \
0      158023            L. Messi   31   Argentina       94         94
1       20801   Cristiano Ronaldo   33    Portugal       94         94
2      190871           Neymar Jr   26      Brazil       92         93
3      193080              De Gea   27       Spain       91         93
4      192985        K. De Bruyne   27     Belgium       91         92
...       ...                 ...  ...         ...      ...        ...
18202  238813        J. Lundstram   19     England       47         65
18203  243165  N. Christoffersson   19      Sweden       47         63
18204  241638           B. Worman   16     England       47         67
18205  246268      D. Walker-Rice   17     England       47         66
18206  246269           G. Nugent   16     England       46         66

                      Club     Value   Wage Preferred Foot  \
0             FC Barcelona  110500.0  565.0           Left
1                 Juventus   77000.0  405.0          Right
2      Paris Saint-Germain  118500.0  290.0          Right
3        Manchester United   72000.0  260.0          Right
4          Manchester City  102000.0  355.0          Right
...                    ...       ...    ...            ...
18202      Crewe Alexandra      60.0    1.0          Right
18203       Trelleborgs FF      60.0    1.0          Right
18204     Cambridge United      60.0    1.0          Right
18205      Tranmere Rovers      60.0    1.0          Right
18206      Tranmere Rovers      60.0    1.0          Right

       International Reputation  Skill Moves Position  Joined  \
0                           5.0          4.0       RF    2004
1                           5.0          5.0       ST    2018
2                           5.0          5.0       LW    2017
3                           4.0          1.0       GK    2011
4                           4.0          4.0      RCM    2015
...                         ...          ...      ...     ...
18202                       1.0          2.0       CM    2017
18203                       1.0          2.0       ST    2018
18204                       1.0          2.0       ST    2017
18205                       1.0          2.0       RW    2018
18206                       1.0          2.0       CM    2018

      Contract Valid Until    Height  Weight  Release Clause
0               2021-01-01  5.583333   159.0        226500.0
1               2022-01-01  6.166667   183.0        127100.0
2               2022-01-01  5.750000   150.0        228100.0
3               2020-01-01  6.333333   168.0        138600.0
4               2023-01-01  5.916667   154.0        196400.0
...                    ...       ...     ...             ...
18202           2019-01-01  5.750000   134.0           143.0
18203           2020-01-01  6.250000   170.0           113.0
18204           2021-01-01  5.666667   148.0           165.0
18205           2019-01-01  5.833333   154.0           143.0
18206           2019-01-01  5.833333   176.0           165.0

[18207 rows x 18 columns]>

In [2]:
x=pd.read_csv ("imdb_movies")
x

FileNotFoundError: [Errno 2] No such file or directory: 'imdb_movies'